twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservice
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: hellow
  mock-tweet-enabled: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 25
  mock-sleep-ms: 5000