twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservice
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: hellow
  mock-tweet-enabled: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 25   
  mock-sleep-ms: 5000
retry-config:
  initialIntervalMs: 1000
  maxIntervalMs: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleepTimeMs: 2000
kafka-config:
  bootStrapServer: localhost:19092, localhost:29092, localhost:39092,
  schemaRegistryUrlKey: schema.registry.url
  schemaRegistryUrl: http://localhost:8081
  topicName: twitter-topic
  topicNameToCreate:
    - twitter-topic
  numOfPartitions: 3
  replicationFactor: 3
kafka-producer-config:
  kafka-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5
